# Generated by Django 5.2.13 on 2026-04-26 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('COPART', 'Copart (USA)'), ('IAAI', 'IAAI (USA)'), ('MANHEIM', 'Manheim (USA)'), ('ADESA', 'ADESA/OpenLane (USA)'), ('ACV', 'ACV Auctions (USA)'), ('BCA', 'BCA Europe'), ('JAPAN', 'Japan Auctions (USS/JAA)'), ('GOVDEALS', 'GovDeals/GSA (USA)'), ('ENCAR', 'Encar (Korea)'), ('KCAR', 'KCar (Korea)'), ('MANUAL', 'Manual Entry')], db_index=True, max_length=16, verbose_name='المصدر')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('vehicles_created', models.PositiveIntegerField(default=0)),
                ('vehicles_updated', models.PositiveIntegerField(default=0)),
                ('vehicles_skipped', models.PositiveIntegerField(default=0)),
                ('vehicles_deleted', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('options_used', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sync_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, help_text='Unique: {lot_id}-{SOURCE}-{COUNTRY}', max_length=128, unique=True, verbose_name='رقم اللوت')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='رقم الهيكل (VIN)')),
                ('dedup_key', models.CharField(blank=True, db_index=True, help_text='VIN if available, else lot_number. Used to prevent duplicates across sources.', max_length=64, null=True, verbose_name='مفتاح إزالة التكرار')),
                ('source_auction', models.CharField(choices=[('COPART', 'Copart (USA)'), ('IAAI', 'IAAI (USA)'), ('MANHEIM', 'Manheim (USA)'), ('ADESA', 'ADESA/OpenLane (USA)'), ('ACV', 'ACV Auctions (USA)'), ('BCA', 'BCA Europe'), ('JAPAN', 'Japan Auctions (USS/JAA)'), ('GOVDEALS', 'GovDeals/GSA (USA)'), ('ENCAR', 'Encar (Korea)'), ('KCAR', 'KCar (Korea)'), ('MANUAL', 'Manual Entry')], db_index=True, default='MANUAL', max_length=16, verbose_name='المزاد المصدر')),
                ('source_country', models.CharField(blank=True, default='US', max_length=4, verbose_name='دولة المزاد')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='رابط السيارة في المزاد')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='سنة الصنع')),
                ('make', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='الماركة')),
                ('model', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='الموديل')),
                ('trim', models.CharField(blank=True, max_length=128, verbose_name='الفئة (Trim)')),
                ('body_style', models.CharField(blank=True, max_length=64, verbose_name='نوع الهيكل')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='اللون')),
                ('interior_color', models.CharField(blank=True, max_length=64, verbose_name='لون الداخلية')),
                ('engine', models.CharField(blank=True, max_length=128, verbose_name='المحرك')),
                ('cylinders', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الأسطوانات')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'بنزين'), ('diesel', 'ديزل'), ('hybrid', 'هجين'), ('electric', 'كهربائي'), ('other', 'أخرى')], default='', max_length=16, verbose_name='نوع الوقود')),
                ('transmission', models.CharField(blank=True, max_length=64, verbose_name='ناقل الحركة')),
                ('drive_type', models.CharField(blank=True, choices=[('fwd', 'FWD'), ('rwd', 'RWD'), ('awd', 'AWD'), ('4wd', '4WD')], default='', max_length=8, verbose_name='نوع الدفع')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='عداد المسافة')),
                ('odometer_unit', models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=4, verbose_name='وحدة العداد')),
                ('odometer_km', models.PositiveIntegerField(blank=True, help_text='Auto-calculated from odometer + unit', null=True, verbose_name='عداد المسافة (كم)')),
                ('title_type', models.CharField(choices=[('clean', 'Clean Title'), ('salvage', 'Salvage Title'), ('rebuilt', 'Rebuilt Title'), ('parts_only', 'Parts Only'), ('certificate', 'Certificate of Title'), ('lien', 'Lien Title'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16, verbose_name='نوع الصك')),
                ('damage_primary', models.CharField(blank=True, max_length=256, verbose_name='الضرر الرئيسي')),
                ('damage_secondary', models.CharField(blank=True, max_length=256, verbose_name='الضرر الثانوي')),
                ('has_keys', models.BooleanField(blank=True, null=True, verbose_name='يوجد مفاتيح')),
                ('runs_drives', models.BooleanField(blank=True, null=True, verbose_name='يعمل ويسير')),
                ('auction_grade', models.CharField(blank=True, help_text='Japanese grade: 5=Excellent, 4=Good, 3=Average', max_length=8, verbose_name='درجة المزاد')),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Auto-calculated score: title_type(30) + runs_drives(20) + has_keys(10) + odometer(20) + damage(20)', null=True, verbose_name='نقاط الجودة (0-100)')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المزايدة الحالية')),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الشراء الفوري')),
                ('estimated_retail_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='القيمة التجزئة التقديرية')),
                ('currency', models.CharField(default='USD', max_length=4, verbose_name='العملة')),
                ('normalized_price_usd', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Auto-converted to USD from any currency', max_digits=12, null=True, verbose_name='السعر بالدولار (موحّد)')),
                ('import_cost_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='bid + auction_fees + shipping + customs + port_fees', max_digits=12, null=True, verbose_name='تقدير تكلفة الاستيراد الكاملة (USD)')),
                ('import_cost_breakdown', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل تكلفة الاستيراد')),
                ('location_city', models.CharField(blank=True, max_length=128, verbose_name='المدينة')),
                ('location_state', models.CharField(blank=True, max_length=64, verbose_name='الولاية/المنطقة')),
                ('location_country', models.CharField(blank=True, default='US', max_length=4, verbose_name='الدولة')),
                ('auction_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ المزاد')),
                ('status', models.CharField(choices=[('active', 'مزاد مفتوح'), ('sold', 'مباع'), ('upcoming', 'قادم'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], db_index=True, default='upcoming', max_length=16, verbose_name='الحالة')),
                ('bid_count', models.PositiveIntegerField(default=0, verbose_name='عدد المزايدات')),
                ('primary_image', models.URLField(blank=True, null=True, verbose_name='الصورة الرئيسية')),
                ('images_json', models.JSONField(blank=True, default=list, verbose_name='قائمة الصور')),
                ('has_360_view', models.BooleanField(default=False, verbose_name='يوجد عرض 360°')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام من المصدر')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='أول ظهور')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='آخر مزامنة')),
                ('sync_source', models.CharField(blank=True, help_text="e.g. 'salvagebid', 'direct', 'bidcars', 'beforward'", max_length=64, verbose_name='مصدر المزامنة')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف (soft delete)')),
            ],
            options={
                'verbose_name': 'سيارة مزاد',
                'verbose_name_plural': 'سيارات المزادات',
                'db_table': 'auction_vehicle',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['source_auction', 'status'], name='auction_veh_source__9e7a89_idx'), models.Index(fields=['make', 'model', 'year'], name='auction_veh_make_e4d618_idx'), models.Index(fields=['normalized_price_usd'], name='auction_veh_normali_a34e34_idx'), models.Index(fields=['title_type', 'quality_score'], name='auction_veh_title_t_3c93f7_idx'), models.Index(fields=['auction_date'], name='auction_veh_auction_14b595_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=64, verbose_name='الماركة')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='الموديل')),
                ('year_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title_types', models.JSONField(blank=True, default=list, help_text="List of acceptable title types e.g. ['clean', 'salvage']")),
                ('sources', models.JSONField(blank=True, default=list, help_text="List of sources to watch e.g. ['COPART', 'IAAI']")),
                ('is_active', models.BooleanField(default=True)),
                ('notify_whatsapp', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تنبيه سعر',
                'verbose_name_plural': 'تنبيهات الأسعار',
                'db_table': 'price_alert',
            },
        ),
    ]
